[toolchain]
anchor_version = "0.32.1"

[features]
seeds = false
skip-lint = false

[programs.devnet]
sentinel_registry = "2fQyCvg9MgiribMmXbXwn4oq587Kqo3cNGCh4x7BRVCk"

[programs.localnet]
sentinel_registry = "2fQyCvg9MgiribMmXbXwn4oq587Kqo3cNGCh4x7BRVCk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/sentinel-dev.json"

[scripts]
test = "pnpm exec ts-mocha -p ./tsconfig.tests.json -t 1000000 tests/**/*.ts"
